using HotelManagement.Domain.Entities;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace HotelManagement.Web.Models.ViewModels.InvoiceModel
{
    public class InvoiceViewModel
    {
        [Display(Name = "Invoice ID")]
        public int InvoiceID { get;  set; }

        [Display(Name = "Booking ID")]
        public int BookingID { get;  set; }

        [Display(Name = "Customer ID")]
        public int CustomerID { get;  set; }

        [Display(Name = "Invoice Date")]
        [DataType(DataType.Date)]
        public DateTime InvoiceDate { get;  set; }

        [Display(Name = "Total Amount")]
        [DataType(DataType.Currency)]
        public decimal TotalAmount { get;  set; }

        [Display(Name = "Amount Paid")]
        [DataType(DataType.Currency)]
        public decimal AmountPaid { get; set; }

        [Display(Name = "Balance Due")]
        [DataType(DataType.Currency)]
        public decimal BalanceDue => TotalAmount - AmountPaid;

        [Display(Name = "Generated By Employee ID")]
        public int GeneratedByEmployeeID { get;  set; }

        [Display(Name = "Invoice Status")]
        public string InvoiceStatus { get; set; }// This should be an enum of the status

        public IEnumerable<SelectListItem>? Bookings { get; set; }
        public IEnumerable<SelectListItem>? Customers { get; set; }
        public IEnumerable<SelectListItem>? Employees { get; set; }

    }
}
